[app]
target ansible_aws_ssm_instance_id=__INSTANCE_ID__

[app:vars]
ansible_connection=amazon.aws.aws_ssm
ansible_aws_ssm_region=ap-northeast-1
ansible_aws_ssm_bucket_name=__TRANSFER_BUCKET__
ansible_aws_ssm_bucket_sse_mode=AES256
ansible_python_interpreter=/usr/bin/python3
